version: '3.7'

services:
  admin-web:
    container_name: admin-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1234:1234
    environment:
      - CHOKIDAR_USEPOLLING=true
